language: java
jdk:
- oraclejdk7
- openjdk6
env:
  global:
    secure: atEs7S8GuQ5dFeoWNNwVTHjwG+uH0gQutgZhuj7Fu5wApBTTEfn7eNtKFuwX9FnYMiD/YbvsL/dabQIzJ1bfUpCE7pJMwxoFq2mFXq5aXuDfsVD797ib7ZzN4uqTQqZpBL+lfaTR+nckLXQH9LsRr2Iwx1Qz29JmvecAUzyljNw=
