language: java
jdk:
- oraclejdk7
- openjdk6
env:
  global:
  - secure: bjb3OYmUEaDRAEfiV365Tg4L4YUqoJvLCfPIifLGHNj1I3udu8xy+SprcqDyTxFLIJqYwTGjn5x63e3WOpKQoGmlxnA2O9a6JSNcNtqBOKLm40zcbJwPQQhhjTU3fcGlA8oLcZC8OLEID7goEoButvjxTao5OjYF80odjAmOJvg=
